# Generated by Django 5.2 on 2025-04-15 05:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE app_review
                ALTER COLUMN uuid SET DEFAULT uuid_generate_v4();
            """,
            reverse_sql="""
                ALTER TABLE app_review
                ALTER COLUMN uuid DROP DEFAULT;
            """,
        ),
    ]
