# Generated by Django 5.2 on 2025-04-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_review_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="date_finished",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="date_started",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="My Review", max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="pub_date",
            field=models.DateTimeField(null=True, verbose_name="date published"),
        ),
        migrations.RenameField(
            model_name="book",
            old_name="pub_date",
            new_name="date_published",
        ),
    ]
