# Generated by Django 5.2 on 2025-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_book_name_book_author_book_date_finished_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
        migrations.AlterField(
            model_name="book",
            name="date_published",
            field=models.DateTimeField(null=True),
        ),
    ]
