# Generated by Django 5.2 on 2025-06-30 04:12

from django.db import migrations


def create_initial_data(apps, _):
    Book = apps.get_model("app", "Book")
    Review = apps.get_model("app", "Review")

    fake_review = """
            Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus 
            ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus 
            duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus 
            fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada 
            lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti 
            sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.
            Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex
            sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis
            convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus 
            fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada
            lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti
            sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.
            Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus 
            ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus
            duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus
            fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada
            lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti
            sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.
            Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus
            ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus
            duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar
            vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl
            malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class
            aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos
            himenaeos.
            """

    book = Book.objects.create(title="Why We Sleep", google_books_id="ZlU3DwAAQBAJ")
    Review.objects.create(
        book=book,
        title="The best book on sleep hygiene",
        text=fake_review,
    )
    book = Book.objects.create(
        title="Hidden Potential",
        google_books_id="WVe_EAAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="There might be other ways to improve",
        text=fake_review,
    )
    book = Book.objects.create(
        title="The Invention of Morel", google_books_id="2I8SAAAAYAAJ"
    )
    Review.objects.create(
        book=book,
        title="Borges masterpiece",
        text=fake_review,
    )
    book = Book.objects.create(
        title="The Selfish Gene",
        google_books_id="WkHO9HI7koEC",
    )
    Review.objects.create(
        book=book,
        title="Or the immortal gene...",
        text=fake_review,
    )
    book = Book.objects.create(
        title="In Order To Live",
        google_books_id="HD7TCwAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="Hidden secrets of North Korea",
        text=fake_review,
    )
    book = Book.objects.create(
        title="The Boy Who Was Raised as a Dog",
        google_books_id="NBapCMJjgEMC",
    )
    Review.objects.create(
        book=book,
        title="Traumatized children and how to possibly help them",
        text=fake_review,
    )
    book = Book.objects.create(
        title="The Headspace Guide to Meditation & Mindfulness",
        google_books_id="wWy7jgEACAAJ",
    )
    Review.objects.create(
        book=book,
        title="The power of mindfulness in your daily life",
        text=fake_review,
    )
    book = Book.objects.create(
        title="Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future",
        google_books_id="Yd99BAAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="How someone made it",
        text=fake_review,
    )
    book = Book.objects.create(
        title="Atomic Habits",
        google_books_id="XfFvDwAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="How someone made it",
        text=fake_review,
    )
    book = Book.objects.create(
        title="Man's Search for Meaning",
        google_books_id="krlkDwAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="Meaning ...",
        text=fake_review,
    )
    book = Book.objects.create(
        title="The Pumpkin Plan",
        google_books_id="T7_4smXjOVsC",
    )
    Review.objects.create(
        book=book,
        title="Focus on what really matters",
        text=fake_review,
    )
    book = Book.objects.create(
        title="Sam Walton: Made In America",
        google_books_id="ggN9Kp8UVfwC",
    )
    Review.objects.create(
        book=book,
        title="Focus on what really matters",
        text=fake_review,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_auto_20250419_2002"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_data, reverse_code=migrations.RunPython.noop
        ),
    ]
