# Generated by Django 5.2 on 2025-06-30 04:12

from django.db import migrations


def create_initial_data(apps, _):
    Book = apps.get_model("app", "Book")
    Review = apps.get_model("app", "Review")

    book = Book.objects.create(title="Why We Sleep", google_books_id="ZlU3DwAAQBAJ")
    Review.objects.create(
        book=book,
        title="The best book on sleep hygiene",
    )
    book = Book.objects.create(
        title="Hidden Potential",
        google_books_id="WVe_EAAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="There might be other ways to improve",
    )
    book = Book.objects.create(
        title="The Invention of Morel", google_books_id="2I8SAAAAYAAJ"
    )
    Review.objects.create(
        book=book,
        title="Borges masterpiece",
    )
    book = Book.objects.create(
        title="The Selfish Gene",
        google_books_id="WkHO9HI7koEC",
    )
    Review.objects.create(
        book=book,
        title="Or the immortal gene...",
    )
    book = Book.objects.create(
        title="In Order To Live",
        google_books_id="HD7TCwAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="Hidden secrets of North Korea",
    )
    book = Book.objects.create(
        title="The Boy Who Was Raised as a Dog",
        google_books_id="NBapCMJjgEMC",
    )
    Review.objects.create(
        book=book,
        title="Traumatized children and how to possibly help them",
    )
    book = Book.objects.create(
        title="The Headspace Guide to Meditation & Mindfulness",
        google_books_id="wWy7jgEACAAJ",
    )
    Review.objects.create(
        book=book,
        title="The power of mindfulness in your daily life",
    )
    book = Book.objects.create(
        title="Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future",
        google_books_id="Yd99BAAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="How someone made it",
    )
    book = Book.objects.create(
        title="Atomic Habits",
        google_books_id="XfFvDwAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="How someone made it",
    )
    book = Book.objects.create(
        title="Man's Search for Meaning",
        google_books_id="krlkDwAAQBAJ",
    )
    Review.objects.create(
        book=book,
        title="Meaning ...",
    )
    book = Book.objects.create(
        title="The Pumpkin Plan",
        google_books_id="T7_4smXjOVsC",
    )
    Review.objects.create(
        book=book,
        title="Focus on what really matters",
    )
    book = Book.objects.create(
        title="Sam Walton: Made In America",
        google_books_id="ggN9Kp8UVfwC",
    )
    Review.objects.create(
        book=book,
        title="How to build an empire",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_auto_20250419_2002"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_data, reverse_code=migrations.RunPython.noop
        ),
    ]
