# Generated by Django 5.2 on 2025-07-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20250630_0412"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="content",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
