name: Pull Request CI

on:
  pull_request:
    branches: [main]

jobs:
  servicetest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5480:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: true
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: test_db
    #   POSTGRES_HOST: localhost
    #   POSTGRES_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: uv pip install --use-uv --system

      - name: Wait for Postgres using pg_isready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5480 && echo "Postgres is ready" && break
            echo "Waiting for Postgres..."
            sleep 3
          done

      - name: Run migrations
        run: |
          python manage.py makemigrations --check --dry-run
          python manage.py migrate

      - name: Run tests
        run: python manage.py test

      - name: Run lint
        run: |
          uv pip install flake8
          flake8 .
